/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs_146_project;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maninderpalsingh
 */
public class SearchAccountInformation extends javax.swing.JFrame {

    /**
     * Creates new form AccountInformation
     */
    public SearchAccountInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        ComboBox_account_balance = new javax.swing.JComboBox();
        balance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        input_customer_information = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        Button_search_accountBalance = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        socialSecurity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+3));
        jLabel5.setText("Total Balance");

        ComboBox_account_balance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Account Number", "id", "Social Security" }));

        balance.setFont(balance.getFont().deriveFont(balance.getFont().getStyle() | java.awt.Font.BOLD, balance.getFont().getSize()+3));
        balance.setText("/");

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getStyle() | java.awt.Font.BOLD, jLabel18.getFont().getSize()+5));
        jLabel18.setText("Search Account Information");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+3));
        jLabel1.setText("First Name");

        firstName.setFont(firstName.getFont().deriveFont(firstName.getFont().getStyle() | java.awt.Font.BOLD, firstName.getFont().getSize()+3));
        firstName.setText("/");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+3));
        jLabel2.setText("Last name");

        lastName.setFont(lastName.getFont().deriveFont(lastName.getFont().getStyle() | java.awt.Font.BOLD, lastName.getFont().getSize()+3));
        lastName.setText("/");

        Button_search_accountBalance.setText("Search");
        Button_search_accountBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_balance_search(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+3));
        jLabel3.setText("Account bumber");

        accountNumber.setFont(accountNumber.getFont().deriveFont(accountNumber.getFont().getStyle() | java.awt.Font.BOLD, accountNumber.getFont().getSize()+3));
        accountNumber.setText("/");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+3));
        jLabel4.setText("Social Security");

        socialSecurity.setFont(socialSecurity.getFont().deriveFont(socialSecurity.getFont().getStyle() | java.awt.Font.BOLD, socialSecurity.getFont().getSize()+3));
        socialSecurity.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(socialSecurity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBox_account_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_customer_information, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Button_search_accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_customer_information, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_search_accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_account_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(firstName)
                        .addGap(18, 18, 18)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(socialSecurity)
                        .addGap(18, 18, 18)
                        .addComponent(balance))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void account_balance_search(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_balance_search
        // TODO add your handling code here:
        
        String sql1,sql2;
        
        ArrayList row = null;
        
        ArrayList account = null;
        
        Database_controller db = new Database_controller();
        
        
        if(ComboBox_account_balance.getSelectedItem() == "Account Number") {
          
            
            sql2 = "SELECT * from Account WHERE AccountNumber='"+ input_customer_information.getText()+"'";
            
            db.set_sql(sql2);
            
            try {
                account = new ArrayList(db.getData_from_Account_table());
            } catch (SQLException ex) {
                Logger.getLogger(SearchCustomerInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.out.println(account);
       
            
             if(account.get(1) !=null) {
                accountNumber.setText(account.get(1).toString());
            }
              if(account.get(2) !=null) {
                  String s = Integer.toString((int) account.get(2));
                balance.setText(s + " $");
                  
            }
              
              sql1 = "SELECT * from Client WHERE SocialSecurity='"+ account.get(0)+"'";
            
            db.set_sql(sql1);
            
            try {
                row = new ArrayList(db.getData_from_client_table());
            } catch (SQLException ex) {
                Logger.getLogger(SearchCustomerInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.out.println(row);
       
            if(row.get(0) !=null) {
                firstName.setText(row.get(0).toString());
            }
            if(row.get(1) !=null)
                lastName.setText(row.get(1).toString());
            
            if(row.get(2) !=null)
                socialSecurity.setText(row.get(2).toString());
            
            
            
        } 
        
        if(ComboBox_account_balance.getSelectedItem() == "id") {
         
        }
        
        if(ComboBox_account_balance.getSelectedItem() == "Social Security") {
        
            sql1 = "SELECT * from Client WHERE SocialSecurity='"+ input_customer_information.getText()+"'";
            
            sql2 = "SELECT * from Account WHERE SocialSecurity='"+ input_customer_information.getText()+"'";
            
            db.set_sql(sql1);
            
            try {
                row = new ArrayList(db.getData_from_client_table());
            } catch (SQLException ex) {
                Logger.getLogger(SearchCustomerInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.out.println(row);
       
            if(row.get(0) !=null) {
                firstName.setText(row.get(0).toString());
            }
            if(row.get(1) !=null)
                lastName.setText(row.get(1).toString());
            
            if(row.get(2) !=null)
                socialSecurity.setText(row.get(2).toString());
            
            db.set_sql(sql2);
            
            try {
                account = new ArrayList(db.getData_from_Account_table());
            } catch (SQLException ex) {
                Logger.getLogger(SearchCustomerInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.out.println(account);
       
            
             if(account.get(1) !=null) {
                accountNumber.setText(account.get(1).toString());
            }
              if(account.get(2) !=null) {
                  String s = Integer.toString((int) account.get(2));
                balance.setText(s + " $");
                  
            }
             
        }
                        
    }//GEN-LAST:event_account_balance_search

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    
    public void runSearchAccountInformation() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAccountInformation().setVisible(true);
            }
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAccountInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_search_accountBalance;
    private javax.swing.JComboBox ComboBox_account_balance;
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField input_customer_information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel socialSecurity;
    // End of variables declaration//GEN-END:variables
}
